### ISSUE TITLE
vocab.db not found error on Mac

### ISSUE THREAD

**Issue by pl98** [xythh/ann2html#3]
Hi, 

I've followed the instructions to install ann2html and move the vocab.db file to the correct location in $HOME/Library/Application Support, but running the program gives a vocab.db not found error.

**Comment by xythh** [comment]
Hi, thank you for letting me know about this. I've been working on a version that gets rid of this installation requirement and some other minor changes.

Could you download it and follow the instructions in the README,not on github but the one included in the download,I've yet to update the Github README.

It should work just fine following the instructions there. Let me know if it works as expected, I do not have a mac to test it out.

**Comment by pl98** [comment]
Unfortunately I'm still getting the vocab.db not found error with the new release. After I unzipped the download, I copied the vocab.db file into the ann2html folder and ran the executable. Is that correct?

**Comment by xythh** [comment]
Yes, that is how it should be ran. I booted  a macos ventura virtual machine and was unable to reproduce this error.

The exact steps that I did were
1. Download ann2html-macos-x86_64,oddly enough I did not have to unzip it? After downloading it from safari I had a folder in my downloads.
2. I copied my vocab.db into the ann2html folder in my downloads.
3. tried to run it by double clicking, did not work as the executable is not signed.
4. opened up the terminal and changed directories into my ann2html folder with `cd ~/Downloads/ann2html`
5. ran `./ann2html` in the terminal
6. it ran without errors and I now had an edit.html file

![image](https://github.com/xythh/ann2html/assets/121327029/70637802-e6fb-497d-a296-4d65b1d74f72)

also unrelated to your issue, this led me to figure out that safari does not show Japanese text correctly unless the html file explicitly tells it that its UTF-8 encoded, odd but I've changed the file to fix this issue.

I hope this helped, let me know if this resolved your issue or not. I could try to boot up a macos ARM vm if you are on one of the newer macbooks and it still does not work.

**Comment by pl98** [comment]
OHH I see the issue now, I didn't realize that the program needed to be run in terminal for it to work because I thought the problem was it being unable to locate the vocab.db file. I was trying this on a newer Macbook but it works there as well. Thank you!!

I also ran into the issue with Safari that you mentioned, what do I need to do to fix this?

**Comment by xythh** [comment]
Good to hear that it works!

The issue with safari is fixed if you download the ann2html 1.5.1 release, I've updated the template file so that it shows correctly in Safari. Simply delete the old ann2html folder and download the new release, it should show correctly in Safari now.

I'll update the documentation to show that you need to run it in the terminal, that isn't obvious and should be better documented on my end. Perhaps I'll look into signing it in the future so that it can be ran without the terminal.

**Comment by pl98** [comment]
Amazing, thank you so much for the quick response on this! I'll close this issue as fixed 😊
